name: Build Configurations

on:
  push:
    paths:
      - "flake.lock"
      - "**.nix"
      - ".github/workflows/build-configurations.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

jobs:
  build-configurations:
    name: Build Configurations
    runs-on: ubuntu-latest
    strategy:
      matrix:
        hostname:
          # ISOs
          - athenas
          - sanctuary
          # servers
          - pandora
          # laptops
          - promethea

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Purge non-nix stuff
        uses: wimpysworld/nothing-but-nix@main
        with:
          hatchet-protocol: cleave

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Remove modules with requireFile
        run: |
          rm -f \
            modules/vmware.nix \
            modules/school/cisco.nix

      - name: Install nix-fast-build
        run: nix profile install nixpkgs#nix-fast-build

      - name: Build ${{ matrix.hostname }}
        run: |
          nix-fast-build --skip-cached --no-nom \
            --flake .#nixosConfigurations.${{ matrix.hostname }}.config.system.build.toplevel
          nix build  -L
