name: Checks

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-flake:
    name: Check Flake
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Purge non-nix stuff
        uses: wimpysworld/nothing-but-nix@main
        with:
          hatchet-protocol: cleave

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Nix store
        uses: nix-community/cache-nix-action@v6
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          gc-max-store-size-linux: 5G
          purge: true
          purge-prefixes: nix-${{ runner.os }}-
          purge-created: 0
          purge-last-accessed: 0
          purge-primary-key: never

      - name: Remove modules
        run: |
          rm -f \
            modules/vmware.nix \
            modules/school/cisco.nix \
            modules/flake/deploy.nix

      - name: Check Flake
        run: nix flake check

  build-configurations:
    name: Build Configuration
    if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' # only run in pull requests and on manual runs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        hostname:
          # ISOs
          - athenas
          - sanctuary
          # servers
          - pandora
          # laptops
          - promethea

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Purge non-nix stuff
        uses: wimpysworld/nothing-but-nix@main
        with:
          hatchet-protocol: cleave

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Remove modules with requireFile
        run: |
          rm -f \
            modules/vmware.nix \
            modules/school/cisco.nix

      - name: Build ${{ matrix.hostname }}
        run: |
          nix build .#nixosConfigurations.${{ matrix.hostname }}.config.system.build.toplevel -L

  build-configurations-success:
    name: Build Configurations Success
    runs-on: ubuntu-latest
    needs: [build-configurations]
    if: ${{ cancelled() || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'failure') }}
    steps:
      - name: Conditionally Fail Required Check
        run: |
          echo "::error::Building a configuration has failed!"
          exit 1
