name: Configurations

on:
  workflow_dispatch:
  pull_request:

jobs:
  generate-matrix:
    uses: ./.github/workflows/_matrix.yml

  build:
    name: Build (${{ matrix.hostname }})
    needs: generate-matrix
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Purge non-Nix files
        uses: wimpysworld/nothing-but-nix@main
        with:
          hatchet-protocol: rampage

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Nix cache
        uses: nix-community/cache-nix-action@v7
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          gc-max-store-size-linux: 5G
          purge: true
          purge-prefixes: nix-${{ runner.os }}-
          purge-created: 0
          purge-last-accessed: 0
          purge-primary-key: never

      - name: Remove unbuildable modules
        run: |
          rm -f \
            modules/vmware.nix \
            modules/school/cisco.nix

      - name: Install nix-fast-build
        run: nix profile install nixpkgs#nix-fast-build

      - name: Build
        run: |
          nix-fast-build --skip-cached --no-nom \
            --flake ".#${{ matrix.output }}.${{ matrix.hostname }}.config.system.build.toplevel"

  success:
    name: Configurations Success
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ cancelled() || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'failure') }}
    steps:
      - name: Conditionally Fail Required Check
        run: |
          echo "::error::Building a configuration has failed!"
          exit 1
