name: Diff

on:
  pull_request:

jobs:
  generate-matrix:
    uses: ./.github/workflows/_matrix.yml

  generate-diffs:
    name: Generate Diffs (${{ matrix.hostname }})
    needs: generate-matrix
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Purge non-Nix files
        uses: wimpysworld/nothing-but-nix@main
        with:
          hatchet-protocol: rampage

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Nix cache
        uses: nix-community/cache-nix-action@v7
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          gc-max-store-size-linux: 5G
          purge: true
          purge-prefixes: nix-${{ runner.os }}-
          purge-created: 0
          purge-last-accessed: 0
          purge-primary-key: never

      - uses: natsukium/nix-diff-action@main
        name: Generate diff (${{ matrix.hostname }})
        with:
          mode: diff-only
          attributes: |
            - displayName: ${{ matrix.hostname }}
              attribute: ${{ matrix.output }}.${{ matrix.hostname }}.config.system.build.toplevel

  post-diff-comment:
    name: Post comment
    runs-on: ubuntu-latest
    needs: generate-diffs
    permissions:
      actions: read
      pull-requests: write
    steps:
      - uses: natsukium/nix-diff-action@main
        with:
          mode: comment-only
